[package]
name = "impl-tools"
version = "0.2.0"
authors = ["Diggory Hardy <git@dhardy.name>"]
edition = "2021"
license = "MIT/Apache-2.0"
description = "Helper macros: autoimpl"
keywords = ["proc-macro", "macro", "derive", "trait", "procedural"]
categories = ["development-tools::procedural-macro-helpers"]
repository = "https://github.com/kas-gui/impl-tools"
readme = "README.md"
documentation = "https://docs.rs/impl-tools/"

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
proc-macro2 = { version = "1.0" }
proc-macro-error = "1.0"

[dependencies.syn]
version = "1.0.14"
# We need 'extra-traits' for equality testing
# We need 'full' for parsing macros within macro arguments
features = ["extra-traits", "full"]

[dev-dependencies]
doc-comment = "0.3.3"
