name: Tests

on:
  push:
    branches: [ master, '[0-9]+.[0-9]+' ]
  pull_request:
    branches: [ master, '[0-9]+.[0-9]+' ]

jobs:
  nightly:
    name: Nightly, format and Doc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@nightly
      - name: Rustfmt check
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - name: Build docs
        run: cargo doc --all-features --all --no-deps
      - name: Test impl-tools-lib
        run: cargo test --manifest-path lib/Cargo.toml --all-features
      - name: Test impl-tools
        run: cargo test --all-features

  beta:
    name: Beta on MacOS
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@beta
      - name: Test impl-tools-lib
        run: cargo test --manifest-path lib/Cargo.toml --all-features
      - name: Test impl-tools
        run: cargo test --all-features

  stable:
    name: Stable on Windows
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Test impl-tools-lib
        run: cargo test --manifest-path lib/Cargo.toml --all-features
      - name: Test impl-tools
        run: cargo test --all-features

  msrv:
    name: MSRV
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@1.58.1
      - name: Test impl-tools-lib
        run: cargo test --manifest-path lib/Cargo.toml --all-features --lib --tests
      - name: Test impl-tools
        run: cargo test --all-features --lib --tests
